apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${APPLICATION_NAME}
  labels:
    monitoring-key: 'middleware'
name: amq-broker
spec:
  endpoints:
  - port: broker-amq-prometheus
    path: /
  selector:
      matchLabels:
        application: amq-broker